image: ubuntu:latest

before_script:
  - apt update && apt install -y gcc python3 python3-pip python3-venv
  - cd setup-scripts
  - source SetupCICD.sh

test-job 1/2:
  stage: test
  script:
    - echo "Testing..."
    - pwd #source setup-scripts/PythonGNN/bin/activate
    - ls setup-scripts
    - cd test
    - pytest

test-job 2/2:
  stage: test
  script:
    -echo "Testing something else..."
