build-job:
  stage: build
  image: ubuntu:latest
  script:
    - apt update && apt install -y gcc python3
    - cd setup-scripts
    - source SetupCICD.sh

test-job1:
  stage: test
  script:
    - echo "Testing..."

