stages:
    - tox-test-matrix
    - build-image 

workflow:
    rules:
        - if: $CI_COMMIT_BRANCH == "master"

.parallel-matrix-cpu:
    parallel:
        matrix:
            - PY:
                - "3.7"
                - "3.8"
                - "3.9"
                - "3.10"
                - "3.11"

tox-test-cpu:
    stage: tox-test-matrix
    parallel: !reference [.parallel-matrix-cpu, parallel]
    image: python:$PY

    variables:
        PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
    cache:
        paths:
            - .cache/pip
            - venv/
    before_script:
        - pip install virtualenv
        - virtualenv venv
        - source venv/bin/activate
    script:
        - pip install tox
        - tox -e $PY

build:
    stage: build-image
    script: 
        - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
        - docker build -t $CI_REGISTRY_IMAGE:latest .
        - docker push $CI_REGISTRY_IMAGE:latest
        
